# config.yaml
program: main.py
method: bayes
name: prediction rnn

metric:
  goal: minimize
  name: val_loss

parameters:

  batch_size:
    values: [32, 64, 128, 256, 512, 1024]
  lr:
    min: 0.0001
    max: 0.1
  weight_decay:
    value: 0.000001
  epochs:
    values: [10, 20, 30, 40, 50,70,90,100]
  seed:
    value: 42
  hidden_size:
    values: [64, 128, 256, 512, 1024]
  num_classes:  # number of classes
    value: 10
  num_layers:
    values: [1, 2, 3, 4, 5,6,7,8]
  num_layers_encoder:
    value: 2
  num_layers_decoder:
    value: 2
  teacher_forcing:
    value: 0.2
  max_norm:
    value: 1.0
  val_split:
    value: 0.2
  out_dir:
    value: "./checkpoints"
  